[[verify]]
pattern = "./src/${path:**/}${file:*}.ts"
commands = [
    ["deno", "lint", "./src/${path}${file}.ts"],
    ["deno", "fmt", "./src/${path}${file}.ts"],
]

[[verify]]
pattern = "./src/${path:**/}${file:*}.ts"
commands = [
    ["deno", "test", "./tests/${path}${file}.test.ts"]
]
requires = [ "./tests/${path}${file}.test.ts" ]
